name: env-reticulate
channels:
  - conda-forge
dependencies:
  - python=3.10
  - graphviz
  - pygraphviz
  - pip
  - pip:
    - pandas
    - scikit-learn
    - networkx
    - matplotlib
    - seaborn
